#!/bin/bash

GEO=`curl http://ip-api.com/json`
LAT=`echo $GEO | jq '.lat'`
LNG=`echo $GEO | jq '.lon'`
URL=https://api.darksky.net/forecast/$DARKSKY_API_KEY/$LAT,$LNG?units=si

FORECAST=`curl $URL`
TEMP=`echo $FORECAST | jq '.currently.temperature'`
COND=`echo $FORECAST | jq -r '.currently.summary'`

echo ${TEMP}C/${COND}

